---
title: Nvdaes.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Comunidad hispanohablante de NVDA
description: NVDA es un lector de pantalla para Windows, de código abierto y gratuito,
  desarrollado por NV Access con la participación de la amplia comunidad de personas
  que lo disfrutan. En este espacio colaborativo compartiremos información generada
  por la comunidad hispanohablante de NVDA. Esperamos que resulte ameno y útil para
  profundizar en el conocimiento y construcción de nuestro lector de pantalla.
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: nvdaes
  instagram: 
  linkedin: 
  pinterest: 
  rss: https://nvdaes.github.io/feed.xml
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: nvdaes-github-io
google_analytics: UA-71732871-2
url: 
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile.lock
- LICENSE
- README.md
- CNAME
authors:
  Noelia:
    name: Noelia
    display_name: Noelia
    web: https://nvdaes.github.io/noelia
  Chris:
    name: Chris
    display_name: Chris
    web: https://nvdaes.github.io/chris
